---
title: "Plotly"
output: 
  html_document:
    toc: true
    toc_float: true
    theme: cosmo
---
This page is about making some plots about NYC Restaurant Inspection Results

Load packages
```{r, encho = FALSE,Warming = FALSE}
library(tidyverse)
library(p8105.datasets)
library(plotly)
```

Load the data
```{r}
data("rest_inspec")
```

## Make a histogram about the number of grade A, B, and C restaurants 
```{r}
rest_inspec %>%
  select(boro, grade) %>% 
  filter(grade == c("A", "B", "C")) %>% 
  group_by(boro, grade) %>% 
  filter(boro !="Missing") %>% 
  summarize(
    count = n()
  ) %>% 
  plot_ly(
    x = ~boro, 
    y = ~count,
    color = ~grade,
    type = "bar",
    colors = "viridis") 
```


## Make boxplot about score of grade A restaurant in different locations
```{r}
rest_inspec %>% 
  select(boro, score, grade) %>% 
  group_by(boro) %>% 
  filter(score != "NA",
         grade == "A",
         boro != "Missing") %>% 
  plot_ly(
    y = ~score,
    color =~boro,
    type = "box",
    colors = "viridis"
  )
```


## Make a scatter plot of status of critical flage for restaurants with different grades
```{r}
rest_inspec %>% 
  select(boro, critical_flag, grade) %>% 
  filter(boro == "MANHATTAN") %>% 
  group_by(grade, critical_flag) %>% 
  summarize(
    count = n()
  ) %>% 
  filter(grade !="Not Yet Graded") %>% 
  mutate(
    critical_flag = forcats::fct_reorder(critical_flag, count))%>% 
  plot_ly(
    x =~critical_flag,
    y =~count,
    color = ~grade,
    type = "scatter",
    mode = "markers"
  )
```

