---
title: "My awesome website"
output: 
  html_document:
    toc: true
    toc_float: true
    theme: cosmo
---
This page is about making some plotly examples

```{r}
library(tidyverse)
library(p8105.datasets)
library(plotly)
```

let's look at the NYC airbnb data
```{r}
data("nyc_airbnb")

nyc_airbnb = 
  nyc_airbnb %>% 
  mutate(rating = review_scores_location / 2) %>%
  select(
    neighbourhood_group, neighbourhood, rating, price, room_type, lat, long) %>%
  filter(
    !is.na(rating), 
    neighbourhood_group == "Manhattan",
    room_type == "Entire home/apt",
    price %in% 100:500) %>% 
  drop_na(rating)
```


## Make a scatterplot

```{r}
nyc_airbnb %>% 
  mutate(
    text_label = str_c("Price:$", price, "\nRating:", rating)
  ) %>% 
  plot_ly(
    x = ~lat, y = ~long, type = "scatter", mode = "markers",
    color = ~price,
    text = ~text_label,
    alpha = .5  )
```

## Plotly boxplot

```{r}
nyc_airbnb %>% 
  mutate(
    neighbourhood = fct_reorder(neighbourhood, price) 
  ) %>% 
  plot_ly(
    y = ~ price, color = ~ neighbourhood, type ="box",
    colors = "viridis"
  )
```

## bar chart

```{r}
nyc_airbnb %>% 
  count(neighbourhood) %>% 
  mutate(neighbourhood = fct_reorder(neighbourhood, n)) %>% 
  plot_ly(x = ~neighbourhood, y = ~n, color = ~neighbourhood, type = "bar", colors = "viridis")
```

## ggplotly
```{r}
gg_lat_long = 
  nyc_airbnb %>% 
  ggplot(
    aes(
      x= lat, 
      y = long,
      color = price)) +
  geom_point()

ggplotly(gg_lat_long)
```

